-- MySQL Script generated by MySQL Workbench
-- lör  8 apr 2017 00:26:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shopdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopdb` DEFAULT CHARACTER SET utf8 ;
USE `shopdb` ;

-- -----------------------------------------------------
-- Table `shopdb`.`lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`lists` (
  `list_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `parent` INT NULL,
  `access` BIT(10) NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`list_id`),
  INDEX `fk_lists_idx` (`parent` ASC),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_lists`
    FOREIGN KEY (`parent`)
    REFERENCES `shopdb`.`lists` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`users` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `uid` INT NOT NULL,
  `access` BIT(10) NOT NULL,
  PRIMARY KEY (`uid`));


-- -----------------------------------------------------
-- Table `shopdb`.`lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`lists` (
  `list_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `parent` INT NULL,
  `access` BIT(10) NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`list_id`),
  INDEX `fk_lists_idx` (`parent` ASC),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_lists`
    FOREIGN KEY (`parent`)
    REFERENCES `shopdb`.`lists` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`tags` (
  `tag_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `access` BIT(10) NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`tag_id`),
  UNIQUE INDEX `tag_UNIQUE` (`name` ASC),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`recipes` (
  `recipe_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NULL,
  `text` VARCHAR(1024) NULL,
  `access` BIT(10) NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`recipe_id`),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`projects` (
  `project_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `priority` INT NOT NULL,
  `finished` DATETIME NULL,
  `access` BIT(10) NOT NULL,
  `assigned_to` INT NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_users_idx` (`assigned_to` ASC),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_users`
    FOREIGN KEY (`assigned_to`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`lists_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`lists_tags` (
  `list_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`list_id`, `tag_id`),
  INDEX `fk_tags_idx` (`tag_id` ASC),
  INDEX `fk_lists_idx` (`list_id` ASC),
  CONSTRAINT `fk_lists`
    FOREIGN KEY (`list_id`)
    REFERENCES `shopdb`.`lists` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `shopdb`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`recipes_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`recipes_tags` (
  `recipe_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `tag_id`),
  INDEX `fk_tags_idx` (`tag_id` ASC),
  INDEX `fk_recipes_idx` (`recipe_id` ASC),
  CONSTRAINT `fk_recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `shopdb`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `shopdb`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`projects_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`projects_tags` (
  `project_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`project_id`, `tag_id`),
  INDEX `fk_tags_idx` (`tag_id` ASC),
  INDEX `fk_projects_idx` (`project_id` ASC),
  CONSTRAINT `fk_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `shopdb`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `shopdb`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`menu` (
  `date` DATE NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `recipe_id` INT NULL,
  `access` BIT(10) NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`date`),
  INDEX `fk_recipes_idx` (`recipe_id` ASC),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `shopdb`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`items` (
  `item_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `unit` VARCHAR(45) NULL,
  `amount` DOUBLE NULL,
  `price` DOUBLE NULL,
  `access` BIT(10) NOT NULL,
  `owner` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_owner_idx` (`owner` ASC),
  CONSTRAINT `fk_owner`
    FOREIGN KEY (`owner`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`items_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`items_tags` (
  `item_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`item_id`, `tag_id`),
  INDEX `fk_tags_idx` (`tag_id` ASC),
  INDEX `fk_items_idx` (`item_id` ASC),
  CONSTRAINT `fk_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `shopdb`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `shopdb`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`recipes_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`recipes_items` (
  `recipe_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`recipe_id`, `item_id`),
  INDEX `fk_items_idx` (`item_id` ASC),
  INDEX `fk_recipes_idx` (`recipe_id` ASC),
  CONSTRAINT `fk_recipes`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `shopdb`.`recipes` (`recipe_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `shopdb`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`lists_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`lists_items` (
  `list_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `num_of` INT NOT NULL,
  PRIMARY KEY (`list_id`, `item_id`),
  INDEX `fk_items_idx` (`item_id` ASC),
  INDEX `fk_lists_idx` (`list_id` ASC),
  CONSTRAINT `fk_lists`
    FOREIGN KEY (`list_id`)
    REFERENCES `shopdb`.`lists` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `shopdb`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`lists_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`lists_items` (
  `list_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `num_of` INT NOT NULL,
  PRIMARY KEY (`list_id`, `item_id`),
  INDEX `fk_items_idx` (`item_id` ASC),
  INDEX `fk_lists_idx` (`list_id` ASC),
  CONSTRAINT `fk_lists`
    FOREIGN KEY (`list_id`)
    REFERENCES `shopdb`.`lists` (`list_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items`
    FOREIGN KEY (`item_id`)
    REFERENCES `shopdb`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`groups` (
  `gid` INT NOT NULL,
  `access` BIT(10) NULL,
  PRIMARY KEY (`gid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shopdb`.`users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopdb`.`users_groups` (
  `uid` INT NOT NULL,
  `gid` INT NOT NULL,
  PRIMARY KEY (`uid`, `gid`),
  INDEX `fk_groups_idx` (`gid` ASC),
  INDEX `fk_users_idx` (`uid` ASC),
  CONSTRAINT `fk_users`
    FOREIGN KEY (`uid`)
    REFERENCES `shopdb`.`users` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups`
    FOREIGN KEY (`gid`)
    REFERENCES `shopdb`.`groups` (`gid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
